version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
      - image: circleci/mongo:3.6
    environment:
      MAPBOX_ACCESS_TOKEN: stubForTest
      MAPQUEST_KEY: stubForTest
      GOOGLE_CLIENT_ID: stubForTest
      GOOGLE_SECRET: stubForTest
      GITHUB_CLIENT_ID: stubForTest
      GITHUB_SECRET: stubForTest
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - h-map-v2-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Run tests
          command: stack test
      - run:
          name: Install executable
          command: stack install
      - save_cache:
          name: Cache Dependencies
          key: h-map-v2-{{ checksum "package.yaml" }}
          paths:
            - ".stack-work"
            - "/root/.stack"
      - store_artifacts: # upload build artifact for display in CircleCi
          path: ~/.local/bin/h-map-exe
destination: h-map-exe
